# Biblioteca Numpy

## Arreglos en Numpy

In [17]:
import numpy as np
#Creando un arreglo de 2*3
data = np.random.randn(2,3)

In [18]:
data

array([[-0.9749845 , -0.6799995 , -0.74899443],
       [-0.34008602,  0.87455436, -0.70724315]])

In [19]:
print(data)

data *10, data + data

[[-0.9749845  -0.6799995  -0.74899443]
 [-0.34008602  0.87455436 -0.70724315]]


(array([[-9.74984504, -6.79999502, -7.48994432],
        [-3.40086022,  8.74554363, -7.07243148]]),
 array([[-1.94996901, -1.359999  , -1.49798886],
        [-0.68017204,  1.74910873, -1.4144863 ]]))

In [20]:
data = [[1,2,3],[4,5,6]]
arr = np.array(data)

In [21]:
#Operraciones como shape o dim
print(arr.shape) #forma en que esat creado el arreglo
print(arr.ndim) #Dimensiones creadas

(2, 3)
2


# Indexando Arreglos

In [22]:
arr = np.arange(8)

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [24]:
arr[5]#Vemos el elemento en la posicion 5

5

In [25]:
arr[2:5]#Desde la pos 2 a la 4

array([2, 3, 4])

In [26]:
arr[:] = 58 #Si asignamos un valorbrocasteado a todo el rango

In [27]:
arr

array([58, 58, 58, 58, 58, 58, 58, 58])

## Slicing

In [28]:
arr2d = np.array([[1,2,3],
                 [4,5,6],
                [7,8,9,]])

In [29]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [32]:
arr2d[1,:2]

array([4, 5])

In [33]:
arr2d[:2,1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

# Arreglos BOOLEANOS

In [34]:
arr2d < 2

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False, False]])

In [35]:
arr2d[arr2d < 2]

array([1, 0, 0, 0, 0])

In [36]:
arr2d > 0

array([[ True, False, False],
       [ True, False, False],
       [ True,  True,  True]])

In [37]:
arr2d[arr2d > 0]

array([1, 4, 7, 8, 9])

# Fuciones Universales

In [44]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
np.sqrt(arr)# Raiz cuadrada de cada 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [40]:
np.abs([-2,1,-3])

array([2, 1, 3])

In [41]:
np.square(arr) #arreglo al cuadrado cada termino

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [42]:
np.add(arr,arr)# add recibe 2 parametros se le pasan 2 arreglos, suma cada elemente 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Funciones de Agregacion

In [49]:
arr = np.random.randn(5,4)
arr
#print(arr)

array([[-0.47479527,  1.45809478,  0.06992477,  0.27482826],
       [ 1.5005195 , -0.58001628,  0.88861827,  1.30414681],
       [ 1.58070367,  0.26569717,  0.18879138, -0.93009127],
       [-0.65841834, -0.16242817, -0.45367515, -0.31827797],
       [-1.39276686, -1.08250467, -1.295445  ,  1.54653546]])

In [50]:
arr.mean() # representa el Promedio de todos los elemntos del arreglo

0.08647205474205732

In [51]:
arr.sum() # representa la suma de todos los elemntos del arreglo

1.7294410948411465